name: Tekken7 Movelist Deploy

on:
  push:
    branches:
      - master

job:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@master
      
      - name: Install dependencies
        uses: npm install
      
      - name: Build
        uses: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northease-2 \
            dist s3://tekken7.aromahyang.com